- shell: "google-chrome --version"
  register: chrome

- name: Get Chrome version
  set_fact:
    this_name: "Chrome"
    this_version: "{{ chrome.stdout.split('.')[0] | replace('Google Chrome ','') }}"
    this_file_name: "chromedriver_{{os_arch}}.zip"

- include_tasks: "fn/append.yml"

- include_tasks: "fn/get_release.yml"

