home: "{{lookup('ansible.builtin.env', 'HOME')}}"
fn: "{{playbook_dir}}/roles/_fn/tasks/"

# User's
project_env: ["{% if project is defined and project %}{{home}}/{{ project.src_path }}/venv{% endif %}"] # if defined and Not empty

# Default
test_env: ["{{ playbook_dir | dirname }}/test/python/venv"]

# Combine user's & default
combined: "{{project_env + test_env}}"

virtual_env: "{{combined | select()}}" # Removes empty list items!
