- name: Create a directory
  ansible.builtin.file:
    path: "{{mirror_dir}}"
    state: directory


- include_tasks: "{{item}}/main.yml"
  loop: "{{browsers.keys()|list}}"

# - debug:
#     msg: "For each : {{item}}"
#   loop: "{{browsers.keys()|list}}"
