# Overwrite to add your own

my_browser: {
  "Chrome": {
    "version": "",
    "file_name": "",
  },
}

future: {
  "Firefox": {
    "version": "",
    "file_name": "",
  },
}

# default_browser: {"Chrome"}
default_browser: {}

browsers: "{{ my_browser | ansible.builtin.combine(default_browser) }}"

# Clear old webdriver, and install from scratch!
reinstall: false