# Overwrite to add your own

my_browser: {
  "Chrome": {
    "version": "",
    "file_name": "",
  },
}

future: {
  "Firefox": {
    "version": "",
    "file_name": "",
  },
}

default_browser: {}

browsers: "{{ my_browser | ansible.builtin.combine(default_browser) }}"

reinstall: false