- name: Create a directory
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  loop:
  - "{{mirror_dir}}"
  - "{{ava_dir}}"


- name: Download WebDriver
  ansible.builtin.get_url:
    url: "{{webdriver[item.key][ item.value.version | int ][os_arch]}}"
    dest: "{{mirror_dir}}/{{browsers[item.key]['file_name']}}"
  loop: "{{ browsers | dict2items }}"


# - debug:
#     msg: "URL {{webdriver[item.key][ item.value.version | int ][os_arch]}}  Dir {{mirror_dir}}/{{browsers[item.key]['file_name']}}"
#     msg: "All : {{browsers.Chrome.version}}"
#   loop: "{{ browsers | dict2items }}"
