- name: Create a directory
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
  loop:
  - "{{mirror_dir}}"
  - "{{ava_dir}}/{{this_driver}}"


- name: Download WebDriver
  ansible.builtin.get_url:
    url: "{{webdriver[item.key][ item.value.version | int ][os_arch]}}"
    dest: "{{mirror_dir}}/{{browsers[item.key]['file_name']}}"
  loop: "{{ browsers | dict2items }}"
