# Future: load from a JSON file instead!

webdriver: {
  "Chrome": {
    "Home": {
      "site": "https://chromedriver.chromium.org/home",
      "release": "https://chromedriver.chromium.org/downloads",
      "doc": {
        "Android": "https://chromedriver.chromium.org/getting-started/getting-started---android"
        },
      },
    114: {
      "status": "Broken on Ubuntu 23.04!",
      "linux64": "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip",
      "macos_arm64": "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac_arm64.zip",
    },
    11490: {
      "linux64": "https://chromedriver.storage.googleapis.com/114.0.5735.16/chromedriver_linux64.zip",
      "macos_arm64": "",
    },
    113: {
      "linux64": "todo",
      "macos_arm64": "todo",
    },
  },
  "Firefox": {
    "Home": {
      "site": "",
      "doc": "https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/firefox.html",
      "release": "https://github.com/mozilla/geckodriver/releases/",
    },
    0.33: {
      "version": 0.33,
      "linux64": "https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux-aarch64.tar.gz",
    },
  }
}

# Defaults
## uni.os:
HOME: "{{lookup('ansible.builtin.env', 'HOME')}}"
mirror_dir: "{{HOME}}/.uni/stor/mirror"
ava_dir: "{{HOME}}/.uni/ava/selenium"

## hw.machine:
arch: "{{'64' if ansible_architecture == 'x86_64'}}"
os: "{{ ansible_system | lower }}"
os_arch: "{{ os }}{{ arch }}"

## blank
webdriver_path: ""