home: "https://chromedriver.chromium.org/downloads"

chrome_driver: {
  114: {
    "version": 114,
    "linux": "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip",
    "macos_arm64": "https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_mac_arm64.zip",
  },
}