- name: Setup Web-Scraping Libraries
  hosts: localhost # , fedora, ubuntu
  vars:
    # Host_vars
    ansible_become_password: u
    ansible_user: "{{lookup('ansible.builtin.env', 'USER')}}"
    #
    reinstall: false # True

  roles:
    - get
    - Beautiful Soup
    - Selenium
    - Requests
