- name: Setup Web-Scraping Libraries
  hosts: localhost # vm
  vars:
    ansible_become_password: u
    #
    reinstall: false # True

  roles:
    - .dep/Browser/Chrome
    - .dep/Browser/Chromium
    - get
    - Beautiful Soup
    - Selenium
    - Requests
